### ISSUE TITLE
[enhancement] add note regarding path traversal attack

### ISSUE THREAD

**Issue by TheAlgorythm** [alilleybrinker/pathbuf#1]
This isn't a particular problem of this crate, rather a missing `push_one` in the standard library, as push allows multiple components. But it would be good to document it also in this crate, so people don't forget about it.

If you want to add a path traversal protected version, have a look at a [implementation by me](https://github.com/TheAlgorythm/pam-auth/blob/MAIN/pam-direct-fallback/src/lib.rs#L39-L73).
Otherwise I will create a crate with this functionality (w\o macro), when I have time, but it could fit to this crate.

**Comment by alilleybrinker** [comment]
Hey, to clarify the issue here is that the components can themselves encode multiple components, so there's no protection against a path traversal attack. I mean I'm pretty happy to document that.

**Comment by TheAlgorythm** [comment]
Yeah exactly. Sorry for not describing the issue properly in the first place.

An example (modified from the `std`-docs) would be:

```Rust
use std::path::PathBuf;

let mut path = PathBuf::from("/tmp");
path.push("../etc/shadow");
assert_eq!(path, PathBuf::from("/tmp/../etc/shadow"));
```

Thanks for your intention of documenting it as people should be aware of it.

**Comment by TheAlgorythm** [comment]
Do you consider an additional version with path traversal protection out of scope?
Otherwise I could do a PR.

**Comment by alilleybrinker** [comment]
Since this issue was specifically about adding documentation, and that's been done in #2, I am going to close this. I'll open another issue for consideration of the implementation question. Thanks @TheAlgorythm!
