### ISSUE TITLE
Consider implementation changes to protect from path traversal attacks.

### ISSUE THREAD

**Issue by alilleybrinker** [alilleybrinker/pathbuf#3]
Right now, as discussed in #1, the macro exposed by this crate leaves users vulnerable to path traversal attacks. However, it doesn't _have_ to do so, and could either be modified, or have an alternative macro that protects against the attack, perhaps optionally with an unsafe version as well.

One version I could imagine would look like:

```
use pathbuf::try_pathbuf;

fn main() -> Result<(), Box<dyn Error>> {
    // This will fail, because "path/with" contains more than one component.
    let path = try_pathbuf!["some", "path/with", "a", "traversal", "issue.md"]?;

    Ok(())
}
```

This basically just rejects multi-part paths as inputs to the macro.

We could also imagine retaining the current `pathbuf` macro under a new name, like `unsafe_pathbuf` or `insecure_pathbuf`, which would include documentation that it should only be used with trusted (non-attacker-controlled) inputs, or else you'd be vulnerable to a path traversal attack.

The benefit some may see of the insecure macro is that you avoid the cost of single-component checking for each input.

**Comment by TheAlgorythm** [comment]
I would propose `Option<PathBuf>` instead of the `Result`.
The remaining question is if it should be secure by default and break compatibility or not.
Ideally you could annotate certain elements to allow multiple components but I was only able to do it with the first element where it will probably be the most important one.

```Rust
#[macro_export]
macro_rules! pathbuf_safe {
    ( $( $part:expr ),* ) => {{
        use std::path::PathBuf;

        let mut temp = PathBuf::with_capacity( $( std::mem::size_of_val($part) + )* 0);

        $(
            temp.push_one($part);
        )*

        temp
    }};
    ( allow $first:expr, $( $part:expr ),* ) => {{
        use std::path::PathBuf;

        let mut temp = PathBuf::with_capacity( $( std::mem::size_of_val($part) + )* 0);

        temp.push($first);
        $(
            temp.push_one($part);
        )*

        temp
    }};

    ($( $part:expr, )*) => {{
        $crate::pathbuf_safe![$($part),*]
    }};

    (allow $( $part:expr, )*) => {{
        $crate::pathbuf_safe![allow $($part),*]
    }};
}
```

This doesn't do any special validation as it is more for UX testing. It would allow something like the following.

```Rust
pathbuf_safe!["a", "b", "c"];
let some_trusted_input = "a/b";
pathbuf_safe![allow some_trusted_input , "c"];
pathbuf_safe!["c", allow some_trusted_input]; // not possible (yet)
```

I will do a PR and start with the validation.
